apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: staging-cert
spec:
  secretName: letsencrypt-staging
  dnsNames:
  - medium.qingping.me
  - qingping.me
  - api.medium.me
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - medium.qingping.me
      - qingping.me
      - api.qingping.me
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer