apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-prod
  spec:
    acme:
      email: missing1989@gmail.com
      privateKeySecretRef:
        name: letsencrypt-prod
      server: https://acme-v02.api.letsencrypt.org/directory
      solvers:
      - http01:
          ingress:
            class: nginx
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-staging
  spec:
    acme:
      email: missing1989@gmail.com
      privateKeySecretRef:
        name: letsencrypt-staging
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      solvers:
      - http01:
          ingress:
            class: nginx
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: prod-cert
    namespace: default
  spec:
    renewBefore: 360h
    duration: 2160h
    dnsNames:
    - qingping.me
    - api.qingping.me
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-prod
    secretName: letsencrypt-prod
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: staging-cert
    namespace: default
  spec:
    dnsNames:
    - qingping.me
    issuerRef:
      kind: ClusterIssuer
      name: letsencrypt-staging
    secretName: letsencrypt-staging
kind: List
