apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # Add upstream for letsencrypt job
    upstream letsencrypt {
      server letsencrypt:80 max_fails=0 fail_timeout=1s;
    }

    server {
      listen 80;
      listen [::]:80;
      server_name  localhost;
      location ^~ /.well-known/acme-challenge/ {
        proxy_pass http://letsencrypt;
      }
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
      error_page  404  /index.html;
    }
      